### ISSUE TITLE
Could not initialize class models.db.common.Generate$

### ISSUE THREAD

**Issue by wassemgtk** [yugolf/play-slick-bootstrap3#2]
[RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class models.db.common.Generate$]

[error] application - 

! @6n4ljno1m - Internal server error, for (GET) [/generate/?slickDriver=slick.driver.MySQLDriver&outputFolder=app1&pkg=models.db.common&schema=saas-project] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class models.db.common.Generate$]]
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:254) ~[play_2.11-2.4.0.jar:2.4.0]
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:180) ~[play_2.11-2.4.0.jar:2.4.0]
    at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.0.jar:2.4.0]
    at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.0.jar:2.4.0]
    at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.0.jar:2.4.0]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [play-netty-server_2.11-2.4.0.jar:2.4.0]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:155) [play-netty-server_2.11-2.4.0.jar:2.4.0]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.6.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) [scala-library-2.11.6.jar:na]
    at scala.util.Try$.apply(Try.scala:191) [scala-library-2.11.6.jar:na]
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class models.db.common.Generate$
    at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:498) ~[play_2.11-2.4.0.jar:2.4.0]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.0.jar:2.4.0]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.0.jar:2.4.0]
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.4.0.jar:2.4.0]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[play_2.11-2.4.0.jar:2.4.0]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[play_2.11-2.4.0.jar:2.4.0]
    at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
    at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[play_2.11-2.4.0.jar:2.4.0]
    at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[play_2.11-2.4.0.jar:2.4.0]
    at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741) ~[play-iteratees_2.11-2.4.0.jar:2.4.0]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class models.db.common.Generate$
    at controllers.Application$$anonfun$generate$1$$anonfun$apply$4.apply(Application.scala:36) ~[classes/:na]
    at controllers.Application$$anonfun$generate$1$$anonfun$apply$4.apply(Application.scala:35) ~[classes/:na]
    at play.api.data.Form.fold(Form.scala:139) ~[play_2.11-2.4.0.jar:2.4.0]
    at controllers.Application$$anonfun$generate$1.apply(Application.scala:31) ~[classes/:na]
    at controllers.Application$$anonfun$generate$1.apply(Application.scala:30) ~[classes/:na]
    at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[play_2.11-2.4.0.jar:2.4.0]
    at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[play_2.11-2.4.0.jar:2.4.0]
    at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[play_2.11-2.4.0.jar:2.4.0]
    at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[play_2.11-2.4.0.jar:2.4.0]
    at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[play_2.11-2.4.0.jar:2.4.0]

**Comment by yugolf** [comment]
When did you see the error?
Did you click "Generate" button after access to "http://localhost:9000/"?

Did you access this page during compiling your application?

If you have this error yet, could you try generate again after you execute "sbt clean" and "sbt run"?

How about H2 Database?
1. command: sbt
2. command: h2-browser
3. command: run
4. access to http://localhost:9000/
5. click "Generate" by slick.driver.H2Driver / app1 / models.db.common / INFORMATION_SCHEMA
